### ISSUE TITLE
Add ability to set location filter parent with external id

### ISSUE THREAD

**Issue by asahaf** [cognitedata/toolkit#1019]
Hi,

ToolKit Version: `0.3.0b3`

LocationFilter only allows setting the parent ID with a system-generated ID rather than external IDs which makes it difficult to build location hierarchy as the ID is not predictable and can't be applied across environments.

**Comment by ronpal** [comment]
Hello @asahaf , this has been remedied in later versions. 

Kindly post your future questions in https://hub.cognite.com/groups/cognite-data-fusion-toolkit-277 if you don't get a response here.

**Comment by doctrino** [comment]
Fixed in 0.3.6
