### ISSUE TITLE
yaml files in function code directories

### ISSUE THREAD

**Issue by nordbyandreas** [cognitedata/toolkit#395]
### If a function code directory contains a .yaml file then the build is not completed correctly. 

It seems like toolkit tries to parse the .yaml file as if it were a configuration file for toolkit.  

### Example: 

Uploading a function code directory that contains `some.yaml`

```
example_function/
  constants.py
  handler.py
  requirements.txt
  some.yaml
```

Leads to this warning: 
`WARNING: the example_function custom_modules\example\functions\example_function\some.yaml is missing the externalId field(s)`

**Comment by gregertw** [comment]
Thanks for reporting @nordbyandreas!
This is likely a bug, yes.
